// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1XzF74grF4PX2aT2KI4yRXd8fYwPypr4',
    appId: '1:81354618966:web:79bd6166c26440ec99a3f7',
    messagingSenderId: '81354618966',
    projectId: 'sebas-app-dev',
    authDomain: 'sebas-app-dev.firebaseapp.com',
    storageBucket: 'sebas-app-dev.firebasestorage.app',
    measurementId: 'G-V7QS4X2HN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKyEUI1eyYX99LwDE4BBRtdhePes3dpjE',
    appId: '1:81354618966:android:43e4bf745f60bd9399a3f7',
    messagingSenderId: '81354618966',
    projectId: 'sebas-app-dev',
    storageBucket: 'sebas-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ovWef_0dySXZqa_tVKHHaokEdtH3QbU',
    appId: '1:81354618966:ios:b70b4ca0d259fca199a3f7',
    messagingSenderId: '81354618966',
    projectId: 'sebas-app-dev',
    storageBucket: 'sebas-app-dev.firebasestorage.app',
    iosBundleId: 'com.sebas.app',
  );
}
